import { useEffect, useState } from "react";
import { ArrowRight, BadgeCheck, Building2, FlaskConical, HeartPulse, Leaf, Pill, Search, ShieldCheck, Stethoscope } from "lucide-react";
import { Link } from "react-router-dom";
import HospitalGrid from "../components/HospitalGrid";
import { getHospitals } from "../api/hospital";
import type { Tenant } from "../types/tenant";

const care=[{icon:Building2,title:"Hospitals",copy:"Find hospitals and clinics near you.",path:"/hospitals"},{icon:Stethoscope,title:"Doctors",copy:"Explore doctors by specialty and location.",path:"/doctors"},{icon:HeartPulse,title:"Home-care nurses",copy:"Book skilled, compassionate care at home.",path:"/nurses"},{icon:Pill,title:"Pharmacies",copy:"Discover trusted pharmacies and services.",path:"/pharmacy"},{icon:FlaskConical,title:"Laboratories",copy:"Find diagnostic and screening services.",path:"/laboratories"},{icon:Leaf,title:"Traditional medicine",copy:"Meet verified traditional-care practitioners.",path:"/traditional-medicine"}];

export default function Home(){
 const [hospitals,setHospitals]=useState<Tenant[]>([]),[filtered,setFiltered]=useState<Tenant[]>([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{getHospitals().then(d=>{const list=Array.isArray(d)?d:[];setHospitals(list);setFiltered(list)}).catch(e=>console.error("Failed to load hospitals",e)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{const k=search.toLowerCase().trim();setFiltered(!k?hospitals:hospitals.filter(h=>[h.name,h.city,h.state,h.hospital_type].some(v=>(v??"").toLowerCase().includes(k))))},[search,hospitals]);
 return <div className="public-page">
  <section className="relative overflow-hidden bg-[#062c2b] text-white">
   <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,rgba(45,212,191,.2),transparent_30%),radial-gradient(circle_at_10%_90%,rgba(14,116,144,.25),transparent_35%)]"/>
   <div className="section-shell relative grid min-h-[660px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-20">
    <div className="relative z-10"><div className="inline-flex items-center gap-2 rounded-full border border-teal-200/20 bg-white/10 px-4 py-2 text-sm font-bold text-teal-100"><BadgeCheck size={17}/>Care, clearly connected</div><h1 className="mt-7 max-w-3xl text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">The right care.<br/><span className="text-teal-300">Closer to you.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300 sm:text-xl">Discover healthcare professionals and services across Africa, or run your healthcare organisation from one connected platform.</p>
     <div className="mt-9 max-w-2xl rounded-[1.25rem] bg-white p-2 shadow-2xl shadow-black/30"><div className="flex items-center gap-3"><Search className="ml-3 shrink-0 text-slate-400" size={21}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search hospitals, city or specialty" className="min-w-0 flex-1 bg-transparent py-3 text-slate-900 outline-none"/><a href="#hospitals" className="hidden rounded-xl bg-teal-700 px-5 py-3 font-bold text-white sm:block">Search</a></div></div>
     <div className="mt-7 flex flex-wrap gap-5 text-sm font-semibold text-slate-300"><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-teal-300"/>Verified profiles</span><span className="flex items-center gap-2"><HeartPulse size={17} className="text-teal-300"/>Patient-first discovery</span></div>
    </div>
    <div className="relative mx-auto w-full max-w-xl lg:ml-auto"><div className="grid grid-cols-2 gap-3"><img src="/images/nurse-bedside.png" alt="African nurse caring for an older patient at home" className="h-[410px] w-full rounded-[2rem] object-cover shadow-2xl"/><div className="space-y-3 pt-12"><img src="/images/traditional-herb-gathering.png" alt="Grandmother and grandson gathering herbs" className="h-52 w-full rounded-[2rem] object-cover shadow-xl"/><div className="rounded-[2rem] bg-teal-300 p-5 text-[#063b38]"><p className="text-3xl font-black">One place</p><p className="mt-1 text-sm font-bold">for modern, home and traditional care.</p></div></div></div></div>
   </div>
  </section>
  <section className="section-shell py-20 lg:py-24"><div className="max-w-2xl"><p className="eyebrow">Explore the marketplace</p><h2 className="section-title mt-3">Care for every stage of life.</h2><p className="body-copy mt-4">Clear pathways help patients find the right provider without mixing public discovery with hospital administration.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{care.map(({icon:Icon,title,copy,path})=><Link to={path} key={path} className="premium-card group p-6 transition hover:-translate-y-1 hover:border-teal-200 hover:shadow-xl"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><Icon size={23}/></div><h3 className="mt-5 text-xl font-extrabold">{title}</h3><p className="mt-2 leading-7 text-slate-600">{copy}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-teal-700">Explore <ArrowRight size={16} className="transition group-hover:translate-x-1"/></span></Link>)}</div></section>
  <section className="bg-white py-20 lg:py-24"><div className="section-shell grid items-center gap-12 lg:grid-cols-2"><div className="grid grid-cols-2 gap-3"><img src="/images/nurse-dressing.png" alt="Nurse dressing a minor injury during a home visit" className="h-72 w-full rounded-[1.75rem] object-cover sm:h-96"/><img src="/images/nurse-feeding.png" alt="Nurse assisting an older patient with a meal" className="mt-10 h-72 w-full rounded-[1.75rem] object-cover sm:h-96"/></div><div><p className="eyebrow">Professional care at home</p><h2 className="section-title mt-3">Skilled nursing, with the comfort of home.</h2><p className="body-copy mt-5">Find independent nurses for recovery support, medication assistance, wound care and daily living—through transparent professional profiles.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/nurses" className="primary-btn">Find a nurse <ArrowRight size={18}/></Link><Link to="/nurse-onboarding" className="secondary-btn">Join as a nurse</Link></div></div></div></section>
  <section className="bg-[#eef8f1] py-20 lg:py-24"><div className="section-shell grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow text-emerald-800">Heritage, presented responsibly</p><h2 className="section-title mt-3">Traditional knowledge. Clearer choices.</h2><p className="body-copy mt-5">Discover verified practitioners and learn about their services, location and approach. HealthOpz supports informed discovery without unsupported treatment claims.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/traditional-medicine" className="primary-btn bg-emerald-800 hover:bg-emerald-900">Explore practitioners <ArrowRight size={18}/></Link><Link to="/traditional-medicine-onboarding" className="secondary-btn">List your practice</Link></div></div><div className="grid grid-cols-2 gap-3"><img src="/images/traditional-river-walk.png" alt="Grandmother and grandson walking home beside a forest river" className="h-72 w-full rounded-[1.75rem] object-cover sm:h-96"/><img src="/images/traditional-preparation.png" alt="Traditional practitioner preparing washed herbs at a clean table" className="mt-10 h-72 w-full rounded-[1.75rem] object-cover sm:h-96"/></div></div></section>
  <section id="hospitals" className="section-shell py-20 lg:py-24"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Healthcare facilities</p><h2 className="section-title mt-3">Hospitals on HealthOpz</h2><p className="mt-3 text-slate-600">Browse facilities or use the search above to narrow the list.</p></div><span className="w-fit rounded-full bg-teal-50 px-4 py-2 text-sm font-extrabold text-teal-800">{filtered.length} hospitals</span></div><div className="mt-10">{loading?<div className="premium-card py-20 text-center text-slate-500">Loading hospitals…</div>:filtered.length?<HospitalGrid hospitals={filtered}/>:<div className="premium-card py-20 text-center"><Building2 className="mx-auto text-slate-300" size={40}/><h3 className="mt-4 text-xl font-bold">No hospitals found</h3><p className="mt-2 text-slate-500">Try a different name, city or specialty.</p></div>}</div></section>
  <section className="section-shell pb-20 lg:pb-24"><div className="overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-12 text-white sm:px-10 lg:flex lg:items-center lg:justify-between lg:px-14"><div><p className="text-sm font-extrabold uppercase tracking-[.18em] text-teal-300">For healthcare organisations</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Your public presence and operations, connected.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-400">Manage patients, people, appointments, billing and reporting in a private hospital workspace.</p></div><Link to="/hospital-onboarding" className="mt-7 inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-teal-400 px-6 py-3 font-black text-slate-950 hover:bg-teal-300 lg:mt-0">Bring your hospital online <ArrowRight size={18}/></Link></div></section>
 </div>
}
