import { ArrowRight, BadgeCheck, BriefcaseMedical, MapPin, Search, Star } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
const nurses=[{id:1,name:"Nurse Amara Okafor",specialty:"Home recovery support",location:"Lagos, Nigeria",rating:4.9,image:"/images/nurse-bedside.png"},{id:2,name:"Nurse Efe Johnson",specialty:"Wound care",location:"Abuja, Nigeria",rating:4.8,image:"/images/nurse-dressing.png"},{id:3,name:"Nurse Grace Mensah",specialty:"Elderly care",location:"Accra, Ghana",rating:5,image:"/images/nurse-feeding.png"},{id:4,name:"Nurse Ada Nwosu",specialty:"Medication support",location:"Port Harcourt, Nigeria",rating:4.7,image:"/images/nurse-medication.png"}];
const services=[["/images/nurse-bedside.png","Recovery at home","Professional bedside support for a calmer recovery."],["/images/nurse-dressing.png","Wound care","Careful, hygienic dressing support from trained nurses."],["/images/nurse-feeding.png","Daily living support","Respectful assistance that protects independence and dignity."],["/images/nurse-medication.png","Medication support","Help following a prescribed medication routine safely."]];
export default function NursesDirectory(){const [search,setSearch]=useState("");const k=search.toLowerCase();const filtered=nurses.filter(x=>[x.name,x.specialty,x.location].some(v=>v.toLowerCase().includes(k)));return <div className="public-page">
<section className="bg-[#082f3a] text-white"><div className="section-shell grid min-h-[590px] items-center gap-12 py-14 lg:grid-cols-2"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2 text-sm font-bold text-cyan-100"><BadgeCheck size={17}/>Professional home care</span><h1 className="display-title mt-6">Care that meets you<br/><span className="text-cyan-300">where you are.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Find skilled African nurses for recovery, elderly support, wound care and prescribed medication assistance at home.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#nurses" className="primary-btn bg-cyan-400 text-slate-950 hover:bg-cyan-300">Find a nurse <ArrowRight size={18}/></a><Link to="/nurse-onboarding" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/20 px-5 py-3 font-bold hover:bg-white/10">Join as a nurse</Link></div></div><img src="/images/nurse-bedside.png" alt="Professional African nurse caring for an elderly man at home" className="h-[390px] w-full rounded-[2rem] object-cover shadow-2xl"/></div></section>
<section className="section-shell py-20"><div className="max-w-2xl"><p className="eyebrow">Home nursing services</p><h2 className="section-title mt-3">Professional support, delivered with dignity.</h2><p className="body-copy mt-4">Choose the support you need and review nurse profiles before making contact.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(([img,title,copy])=><article key={title} className="premium-card overflow-hidden"><img src={img} alt="" className="h-52 w-full object-cover"/><div className="p-5"><h3 className="text-lg font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></div></article>)}</div></section>
<section id="nurses" className="bg-white py-20"><div className="section-shell"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">Nurse directory</p><h2 className="section-title mt-3">Find the right nurse.</h2></div><div className="search-control w-full lg:max-w-md"><Search className="shrink-0 text-slate-400" size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, service or location" className="min-w-0 flex-1 bg-transparent py-3 outline-none"/></div></div><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{filtered.map(n=><article key={n.id} className="premium-card overflow-hidden"><img src={n.image} alt={n.name} className="h-52 w-full object-cover"/><div className="p-5"><span className="inline-flex items-center gap-1 rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-800"><BadgeCheck size={13}/>Profile verified</span><h3 className="mt-4 text-xl font-extrabold">{n.name}</h3><p className="mt-2 flex items-center gap-2 text-sm font-semibold text-teal-800"><BriefcaseMedical size={16}/>{n.specialty}</p><p className="mt-2 flex items-center gap-2 text-sm text-slate-500"><MapPin size={16}/>{n.location}</p><p className="mt-3 flex items-center gap-1 text-sm font-bold"><Star size={16} fill="currentColor" className="text-amber-400"/>{n.rating}</p><button className="mt-5 w-full rounded-xl bg-teal-700 py-3 font-bold text-white hover:bg-teal-800">View nurse profile</button></div></article>)}</div></div></section></div>}

