import { ArrowRight, Leaf, MapPin, Search, ShieldCheck, Star } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
const practitioners=[{id:1,name:"Mama Adesuwa Herbal Clinic",specialty:"Herbal wellness practice",location:"Benin City, Nigeria",rating:4.9,image:"/images/traditional-preparation.png"},{id:2,name:"Kofi Natural Wellness",specialty:"Natural therapy",location:"Accra, Ghana",rating:4.8,image:"/images/traditional-herb-gathering.png"},{id:3,name:"Ubuntu Wellness Centre",specialty:"Traditional wellness",location:"Johannesburg, South Africa",rating:4.7,image:"/images/traditional-patient.png"},{id:4,name:"Okeke Traditional Practice",specialty:"Traditional bone care",location:"Onitsha, Nigeria",rating:5,image:"/images/traditional-river-walk.png"}];
const story=[["/images/traditional-herb-gathering.png","Gathering","Knowledge begins with careful identification and responsible sourcing."],["/images/traditional-river-walk.png","From place to practice","Heritage is shaped by family, community and the natural environment."],["/images/traditional-preparation.png","Careful preparation","Clean handling and clear conversations help patients make informed choices."],["/images/traditional-patient.png","Personal consultation","Practitioners should explain their approach without unsupported promises."]];
export default function TraditionalMedicine(){const [search,setSearch]=useState("");const k=search.toLowerCase();const filtered=practitioners.filter(x=>[x.name,x.specialty,x.location].some(v=>v.toLowerCase().includes(k)));return <div className="public-page">
<section className="bg-[#143c2c] text-white"><div className="section-shell grid min-h-[590px] items-center gap-12 py-14 lg:grid-cols-2"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-emerald-300">Traditional medicine marketplace</p><h1 className="display-title mt-5">Rooted in heritage.<br/><span className="text-emerald-300">Presented with care.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-emerald-50/80">Explore practitioner profiles, approaches and locations with the clarity you need to make an informed choice.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#practitioners" className="primary-btn bg-emerald-500 text-emerald-950 hover:bg-emerald-400">Find a practitioner <ArrowRight size={18}/></a><Link to="/traditional-medicine-onboarding" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/20 px-5 py-3 font-bold text-white hover:bg-white/10">List your practice</Link></div><p className="mt-6 flex items-center gap-2 text-sm text-emerald-100/70"><ShieldCheck size={17}/>Profiles support discovery and do not replace medical advice.</p></div><img src="/images/traditional-herb-gathering.png" alt="Elderly African woman and grandson gathering herbs in a lush forest" className="h-[390px] w-full rounded-[2rem] object-cover shadow-2xl"/></div></section>
<section className="section-shell py-20"><div className="max-w-2xl"><p className="eyebrow text-emerald-800">A living tradition</p><h2 className="section-title mt-3">A story of knowledge, preparation and trust.</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{story.map(([img,title,copy])=><article key={title} className="premium-card overflow-hidden"><img src={img} alt="" className="h-52 w-full object-cover"/><div className="p-5"><h3 className="text-lg font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></div></article>)}</div></section>
<section id="practitioners" className="bg-white py-20"><div className="section-shell"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow text-emerald-800">Practitioner directory</p><h2 className="section-title mt-3">Explore verified profiles.</h2></div><div className="search-control w-full lg:max-w-md"><Search className="shrink-0 text-slate-400" size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, approach or location" className="min-w-0 flex-1 bg-transparent py-3 outline-none"/></div></div><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{filtered.map(p=><article key={p.id} className="premium-card overflow-hidden"><img src={p.image} alt={p.name} className="h-52 w-full object-cover"/><div className="p-5"><span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800"><ShieldCheck size={13}/>Profile verified</span><h3 className="mt-4 text-xl font-extrabold">{p.name}</h3><p className="mt-2 flex items-center gap-2 text-sm font-semibold text-emerald-800"><Leaf size={16}/>{p.specialty}</p><p className="mt-2 flex items-center gap-2 text-sm text-slate-500"><MapPin size={16}/>{p.location}</p><p className="mt-3 flex items-center gap-1 text-sm font-bold"><Star size={16} fill="currentColor" className="text-amber-400"/>{p.rating}</p><button className="mt-5 w-full rounded-xl bg-emerald-800 py-3 font-bold text-white hover:bg-emerald-900">View profile</button></div></article>)}</div></div></section></div>}

