"""tenant branding and slug support

Revision ID: 301998108182
Revises: 5417a5db0014
Create Date: 2026-07-16 17:10:18.197244

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "301998108182"
down_revision: Union[str, Sequence[str], None] = "5417a5db0014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("slug", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("logo", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("website", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("address", sa.Text(), nullable=True))
    op.add_column("tenants", sa.Column("city", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("state", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("country", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("primary_color", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("secondary_color", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("favicon", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("hero_image", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("about", sa.Text(), nullable=True))
    op.add_column("tenants", sa.Column("facebook", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("instagram", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("linkedin", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("twitter", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("is_verified", sa.Boolean(), nullable=True))
    op.add_column("tenants", sa.Column("subscription_plan", sa.String(), nullable=True))
    op.add_column(
        "tenants", sa.Column("subscription_status", sa.String(), nullable=True)
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_column("tenants", "subscription_status")
    op.drop_column("tenants", "subscription_plan")
    op.drop_column("tenants", "is_verified")
    op.drop_column("tenants", "twitter")
    op.drop_column("tenants", "linkedin")
    op.drop_column("tenants", "instagram")
    op.drop_column("tenants", "facebook")
    op.drop_column("tenants", "about")
    op.drop_column("tenants", "hero_image")
    op.drop_column("tenants", "favicon")
    op.drop_column("tenants", "secondary_color")
    op.drop_column("tenants", "primary_color")
    op.drop_column("tenants", "country")
    op.drop_column("tenants", "state")
    op.drop_column("tenants", "city")
    op.drop_column("tenants", "address")
    op.drop_column("tenants", "website")
    op.drop_column("tenants", "logo")
    op.drop_column("tenants", "slug")
    # ### end Alembic commands ###
