"""tenant profile fields

Revision ID: 794efd09dc25
Revises: 301998108182
Create Date: 2026-07-21 16:09:23.774253

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "794efd09dc25"
down_revision: Union[str, Sequence[str], None] = "301998108182"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("hospital_type", sa.String(), nullable=True))
    op.add_column(
        "tenants", sa.Column("registration_number", sa.String(), nullable=True)
    )
    op.add_column("tenants", sa.Column("license_number", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("contact_person", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("contact_position", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("latitude", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("longitude", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("timezone", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("currency", sa.String(), nullable=True))
    op.alter_column("tenants", "slug", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tenants", "slug", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("tenants", "currency")
    op.drop_column("tenants", "timezone")
    op.drop_column("tenants", "longitude")
    op.drop_column("tenants", "latitude")
    op.drop_column("tenants", "contact_position")
    op.drop_column("tenants", "contact_person")
    op.drop_column("tenants", "license_number")
    op.drop_column("tenants", "registration_number")
    op.drop_column("tenants", "hospital_type")
    # ### end Alembic commands ###
